In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("companies.csv")
df.head()

,name,domain,company_size,location,year_founded,website
0,MEDINIS Eduphygital Basaveshwara Engineering C...,Education Industry,NaN,"Bagalkote, Karnataka, India",2015,https://eduphygital.com
1,Agraja Builders & Developers,Construction & Engineering,NaN,"Dakshina Kannada, Karnataka, India",2008,https://agrajabuilders.com/
2,Gully System Pvt Ltd,IT Industry,NaN,"Bangalore Rural, Karnataka, India",2021,https://www.gullysystem.com
3,JustBreathe - Beinnature Consultancy Pvt Ltd,Manufacturing,NaN,"Bengaluru Urban, Karnataka, India",2019,https://www.justbreathe.in/
4,Creo IT Private Limited,IT Industry,NaN,"Shimoga, Karnataka, India",2010,https://www.creoit.com/

In [3]:
df.drop(columns=['company_size'],inplace=True)

In [4]:
df[df["domain"]=="IT Industry"].head()

,name,domain,location,year_founded,website
2,Gully System Pvt Ltd,IT Industry,"Bangalore Rural, Karnataka, India",2021,https://www.gullysystem.com
4,Creo IT Private Limited,IT Industry,"Shimoga, Karnataka, India",2010,https://www.creoit.com/
6,Ciqur24 LLC (CYBWK PVT LTD),IT Industry,"Bengaluru Urban, Karnataka, India",2022,https://ciqur24.com/
8,Snipe Tech Pvt Ltd,IT Industry,"Bengaluru Urban, Karnataka, India",2009,https://www.snipe.co.in/
9,BluePixel IT Services,IT Industry,"vijayapura, Karnataka, India",2025,NaN

In [5]:
df[['district','state','country']] = df['location'].str.split(',', expand=True)

df['district'] = df['district'].str.strip()
df['state'] = df['state'].str.strip()
df['country'] = df['country'].str.strip()
df.drop(columns=["location"],inplace=True)

In [6]:
df.head()

,name,domain,year_founded,website,district,state,country
0,MEDINIS Eduphygital Basaveshwara Engineering C...,Education Industry,2015,https://eduphygital.com,Bagalkote,Karnataka,India
1,Agraja Builders & Developers,Construction & Engineering,2008,https://agrajabuilders.com/,Dakshina Kannada,Karnataka,India
2,Gully System Pvt Ltd,IT Industry,2021,https://www.gullysystem.com,Bangalore Rural,Karnataka,India
3,JustBreathe - Beinnature Consultancy Pvt Ltd,Manufacturing,2019,https://www.justbreathe.in/,Bengaluru Urban,Karnataka,India
4,Creo IT Private Limited,IT Industry,2010,https://www.creoit.com/,Shimoga,Karnataka,India

## EDA